#!/usr/bin/env bash

# Usage: __gen_dir_alias "$directoryPath"
function __gen_dir_alias() {
    dir="$*"
    [[ "$dir" == "/" ]] && echo "/" && return

    aliasesStr=$(alias | cut -d "=" -f 1)
    aliasArr=()
    while read -r line; do
        line=${line/#alias /}
        aliasArr+=("$line")
    done <<< "$aliasesStr"

    aliasExists=true
    tempAliasName="$(basename "${dir}")"
    tempAliasName=$(echo "${tempAliasName}" | tr '[:upper:]' '[:lower:]')    # to lower
    tempAliasName=${tempAliasName// /}  # remove spaces
    aliasName="${tempAliasName}"

    i=0
    while true; do

        aliasExists=false
        for aname in "${aliasArr[@]}"; do
            [[ "$aname" == "$aliasName" ]] && aliasExists=true && break
        done
        [[ $aliasExists == false ]] && break
        
        i=$((i + 1))
        aliasName="$tempAliasName$i"
    done

    echo "${aliasName}"
}