#!/bin/bash -i
# -i : alias command required interactive more to work on ubuntu

#shellcheck disable=SC2155
#shellcheck disable=SC1091

# Usage: __gen_dir_alias "$directoryPath"
function __gen_dir_alias() {

    source __to_lower
    source __remove_spaces

    local dir="$*"
    [[ "$dir" == "/" ]] && echo "/" && return

    local aliasesStr=$(alias | cut -d "=" -f 1)
    local aliasArr=()
    local line=""

    while read -r line; do
        line=${line/#alias /}
        aliasArr+=("$line")
    done <<< "$aliasesStr"

    local aliasExists=true
    local tempAliasName="$(__remove_spaces "$(__to_lower "$(basename "${dir}")")")"
    local aliasName="${tempAliasName}"

    i=0
    while true; do

        aliasExists=false
        for aname in "${aliasArr[@]}"; do
            [[ "$aname" == "$aliasName" ]] && aliasExists=true && break
        done
        [[ $aliasExists == false ]] && break
        
        i=$((i + 1))
        aliasName="$tempAliasName$i"
    done

    echo "${aliasName}"
}