#!/usr/bin/env bash

#shellcheck disable=SC1091

source __apply_tput

# Usage: __print_as "bold" "red" "Your Text"
function __print_as() {

    while [[ $# -gt 1 ]]; do
        __apply_tput "$1"
        shift
    done

    msg="$1"
    printf "%s" "$msg"

    tput sgr 0
}