#!/bin/bash

# Usage : __split_str "str" "substr"
# str : input string
# substr : delimiter substring
# Output: RESULT_ARR
function __split_str() {
	local str="${1}"
	local delim="${2}"
	local prefix=""

	RESULT_ARR=()
	while [[ "${str}" != "${prefix}" ]]; do
		prefix=${str%$delim*}			# remove suffix
		str=${str#"$prefix$delim"}		# remove prefix
		RESULT_ARR+=("$prefix")
	done
}
