#!/bin/bash

# Usage : __split_str "str" "substr"
# str : input string
# substr : delimiter substring
# Output: RESULT_ARR
function __split_str() {
	local delim="${2}"
	local str="${1}${delim}"
	local prefix=""

	RESULT_ARR=()
	while [[ -n "${str}" ]]; do
		prefix=${str%$delim*}			# remove suffix
		str=${str#"$prefix$delim"}		# remove prefix
		RESULT_ARR+=("$prefix")
	done
}
