#!/usr/bin/env bash

# Usage: __trim_double_quotes "${str}"
# Output: str without preceeding and trailing double quotes
# Example:
#   Input: "Input String"
#   Output: Input String
function __trim_double_quotes() {
    str="${1}"
    str=${str/%\"/}	    # replace suffix
    str=${str/#\"/}     # replace prefix
    echo "${str}"
}