#!/usr/bin/env bash

#shellcheck disable=SC2001
#shellcheck disable=SC2088
#shellcheck disable=SC2162
#shellcheck disable=SC1091
#shellcheck disable=SC1090
#shellcheck disable=SC2155
#shellcheck disable=SC2207

function chd() {

    if [[ $# -gt 0 ]]; then
        cd "$*" || { echo "[Error] couldn't enter \"$*\""; }
        return
    fi

    local RESULT_ARR=()

    source "$__CUSTOM_CONSOLE_UTIL"/__gen_dir_alias
    source "$__CUSTOM_CONSOLE_UTIL"/__print_chd_aliases
    source "$__CUSTOM_CONSOLE_UTIL"/__print_as
    source "$__CUSTOM_CONSOLE_UTIL"/__add_chd_alias
    source "$__CUSTOM_CONSOLE_UTIL"/__get_last_modified_time
    source "$__CUSTOM_CONSOLE_UTIL"/__get_chd_list_item
    source "$__CUSTOM_CONSOLE_UTIL"/__url_encode
    source "$__CUSTOM_CONSOLE_UTIL"/__url_decode
    source "$__CUSTOM_CONSOLE_UTIL"/__split_str
    source "$__CUSTOM_CONSOLE_UTIL"/__escape_spaces

    while true; do

        local itemList=()
        [[ "${PWD}" != "/" ]] && itemList+=('..')
        itemList+=('<<-->>')

        local lsEncodedStr="$(__url_encode "$(ls -pt -1)")"
        __split_str "$lsEncodedStr" "%0A"   # "%0A" is the encoded string for line feed
        local lsEncodedArr=("${RESULT_ARR[@]}")
        local lsItem=""
        local item=""
        local lsArr=()

        for lsItem in "${lsEncodedArr[@]}"; do
            lsItem="$(__url_decode "${lsItem}")"
            lsArr+=("${lsItem}")
            item="$(__get_chd_list_item "${lsItem}")"
            itemList+=("${item}")
        done

        itemList+=(
            '-'
            '~/'
            'ADD ALIAS'
            'SHOW ALIASES'
            'EDIT ALIASES'
        )

        __print_as bold rev "PWD: ${PWD}"
        item="$(printf "%s\n" "${itemList[@]}" | fzf --color 'fg:27' --preview 'tree -L 2 {}')"
        [[ -z "${item}" ]] && break

        [[ "${item}" == "<<-->>" ]] && {
            __print_as bold rev "Frequently Visited Directories"
            item="$(z -l | sed -e 's/^[0-9 ]*//' | fzf --color 'fg:27' --preview 'tree -L 2 {}')"
            [[ -z "${item}" ]] && continue
        }

        [[ "${item:0:1}" == "~" ]] && item="$HOME${item:1}"

        case "${item}" in
            '-')
                cd - &> /dev/null || { echo "[ERROR] couldn't go back to the previous directory"; }
            ;;
            'ADD ALIAS')
                __add_chd_alias
                echo
            ;;

            'SHOW ALIASES')
                __print_chd_aliases
                return 0
            ;;

            'EDIT ALIASES')
                openfile "$__CHD_ALIASES_FILE"
            ;;

            *)
                for lsItem in "${lsArr[@]}"; do
                    local it="$(__get_chd_list_item "${lsItem}")"
                    if [[ "${it}" == "${item}" ]]; then
                        item=${lsItem}
                        break
                    fi
                done

                [[ -d "${item}" && ! -f "${item}" ]] && {
                    cd "$item" || { echo "[ERROR] couldn't enter $item"; }
                    continue
                }
                [[ -f "${item}" && ! -d "${item}" ]] && {
                    openfile "${item}"
                    continue
                }
                echo "[ERROR] Unhandled item :- ${item}"
                return 1
            ;;
        esac
    done

    return 0
}


