#!/usr/bin/env bash

#shellcheck disable=SC2001
#shellcheck disable=SC2088
#shellcheck disable=SC2162
#shellcheck disable=SC1091
#shellcheck disable=SC1090
#shellcheck disable=SC2155
#shellcheck disable=SC2207

function chd() {

    if [[ $# -gt 0 ]]; then
        cd "$*" || { echo "[Error] couldn't enter $*"; }
        return
    fi

    local RESULT_ARR=()

    source __gen_dir_alias
    source __print_chd_aliases
    source __print_as
    source __add_chd_alias
    source __get_last_modified_time
    source __get_chd_list_item
    source __url_encode
    source __url_decode
    source __split_url_encoded_str
    source __escape_spaces

    while true; do

        local itemList=()
        [[ "${PWD}" != "/" ]] && itemList+=('..')
        itemList+=('<-->')

        local lsEncodedStr="$(__url_encode "$(ls -pt -1)")"
        __split_url_encoded_str "$lsEncodedStr" "%0A" "lsEncodedArr"
        local lsEncodedArr=("${RESULT_ARR[@]}")
        local lsItem=""
        local item=""
        local lsArr=()

        for lsItem in "${lsEncodedArr[@]}"; do
            lsItem="$(__url_decode "${lsItem}")"
            lsArr+=("${lsItem}")
            item="$(__get_chd_list_item "${lsItem}")"
            itemList+=("${item}")
        done

        itemList+=(
            '-'
            '~/'
            'ADD ALIAS'
            'SHOW ALIASES'
            'EDIT ALIASES'
        )

        __print_as bold rev "PWD: ${PWD}"
        item="$(printf "%s\n" "${itemList[@]}" | fzf --color 'fg:27' --preview 'ls -pt -1 {}')"
        [[ -z "${item}" ]] && break

        [[ "${item}" == "<-->" ]] && {
            __print_as bold rev "Director Stack"
            item="$(dirs -pl | fzf --color 'fg:27' --preview 'ls -pt -1 {}')"
            [[ -z "${item}" ]] && continue
        }

        [[ "${item:0:1}" == "~" ]] && item="$HOME${item:1}"

        case "${item}" in
            '-')
                cd - &> /dev/null || { echo "[ERROR] couldn't go back to the previous directory"; }
            ;;
            'ADD ALIAS')
                __add_chd_alias
                echo
            ;;

            'SHOW ALIASES')
                __print_chd_aliases
                return 0
            ;;

            'EDIT ALIASES')
                openfile "$__CHD_ALIASES_FILE"
            ;;

            *)
                for lsItem in "${lsArr[@]}"; do
                    local it="$(__get_chd_list_item "${lsItem}")"
                    if [[ "${it}" == "${item}" ]]; then
                        item=${lsItem}
                        break
                    fi
                done

                [[ -d "${item}" && ! -f "${item}" ]] && {
                    cd "$item" || { echo "[ERROR] couldn't enter $item"; }
                    continue
                }
                [[ -f "${item}" && ! -d "${item}" ]] && {
                    openfile "${item}"
                    continue
                }
                echo "[ERROR] Unhandled item :- ${item}"
                return 1
            ;;
        esac
    done

    return 0
}


