#!/usr/bin/env bash

# shellcheck disable=SC2001
# shellcheck disable=SC2088
# shellcheck disable=SC2162
# shellcheck disable=SC1091
# shellcheck disable=SC1090

source __gen_dir_alias
source __print_chd_aliases
source __println_as
source __add_chd_alias

function chd() {

    if [[ $# -gt 0 ]]; then
        cd "$*" || { echo "[Error] couldn't enter $*"; }
        return
    fi

    while true; do
        printf "$(tput bold)$(tput rev)%s" "PWD: ${PWD}$(tput sgr0)"

        itemList=()
        [[ "${PWD}" != "/" ]] && itemList+=('..')
        itemList+=('<-->')

        dirContent=$(ls -t)
        [[ ${#dirContent[@]} -gt 0 ]] && itemList+=("${dirContent[@]}")
        # for f in "${dirContent[@]}"; do
        #     echo "${f}"
        #     itemList+=("${dirContent[@]}")
        # done

        itemList+=(
            '-'
            '~/'
            'ADD ALIAS'
            'SHOW ALIASES'
            'EDIT ALIASES'
        )

        item="$(printf "%s\n" "${itemList[@]}" | fzf --color 'fg:27')"
        [[ "${item}" == "<-->" ]] && item="$(dirs -p | fzf --color 'fg:27')"

        [[ -z "${item}" ]] && break

        [[ "${item:0:1}" == "~" ]] && item="$HOME${item:1}"

        case "${item}" in
            '-')
                cd - &> /dev/null || { echo "[ERROR] couldn't go back to the previous directory"; }
            ;;
            'ADD ALIAS')
                __add_chd_alias
                echo
            ;;

            'SHOW ALIASES')
                __print_chd_aliases
                return 0
            ;;

            'EDIT ALIASES')
                openfile "$__CHD_ALIASES_FILE"
            ;;

            *)
                [[ -d "${item}" && ! -f "${item}" ]] && {
                    cd "$item" || { echo "[ERROR] couldn't enter $item"; }
                    continue
                }
                [[ -f "${item}" && ! -d "${item}" ]] && {
                    openfile "${item}"
                    continue
                }
                echo "[ERROR] Unhandled item :- ${item}"
                return 1
            ;;
        esac
    done

    return 0
}


