#!/usr/bin/env bash

#shellcheck disable=1091
source "$CUSTOM_CONSOLE_UTIL"/__trim_escaped_quotes

# Usage: getrawstr "Input String"
# Output: "Input\ String"
function main() {
    rawFile="$(printf "%q" "${1}")"
    __trim_escaped_quotes "${rawFile}"
}

main "$*"
