#!/usr/bin/env bash

#shellcheck disable=SC1091

function main() {

    source __is_mac_os

    if [[ $(__is_mac_os) == true ]]; then
        open "$*"
    else
        xdg-open "$*"
    fi
}

main "$*"
